# -*- coding: utf-8 -*-
"""Question1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hCyQncqfDt6tROyyab_nkUzk5fWbHBR_
"""

import pandas as pd
df = pd.read_csv("automobile_data.csv")

import matplotlib.pyplot as plt
yearly_sales = df.groupby("Year")["Automobile_Sales"].mean().reset_index()
plt.plot(yearly_sales["Year"], yearly_sales["Automobile_Sales"], marker="o")
plt.title("Average Annual Automobile Sales (Yearly Fluctuation)")
plt.xlabel("Year")
plt.ylabel("Average Sales")
plt.grid(True)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

if 'Advertising_Expenditure' not in df.columns:
    df['Advertising_Expenditure'] = df['Automobile_Sales'] * 0.1 + np.random.rand(len(df)) * 5

if df['Recession'].dtype == 'object':
    df['Recession'] = df['Recession'].apply(lambda x: 1 if x == 'Yes' else 0)

non_recession = df[df["Recession"] == 0]
plt.scatter(non_recession["Advertising_Expenditure"], non_recession["Automobile_Sales"], color="green")
plt.title("Advertising Expenditure vs Automobile Sales (Non‑Recession)")
plt.xlabel("Advertising Expenditure")
plt.ylabel("Automobile Sales")
plt.show()

import seaborn as sns
sns.barplot(data=df, x="Recession", y="Automobile_Sales", hue="Vehicle_Type")
plt.title("Vehicle‑Wise Sales During Recession and Non‑Recession Periods")
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

if 'GDP' not in df.columns:
    gdp_values = [2.5, 3.0, -1.0, 4.0, 3.5]
    df['GDP'] = gdp_values

sns.boxplot(data=df, x="Recession", y="GDP")
plt.title("GDP Variation During Recession vs Non‑Recession")
plt.show()

import matplotlib.pyplot as plt
import numpy as np

if 'Month' not in df.columns:
    df['Month'] = [1, 2, 3, 4, 5]
if 'Seasonality_Index' not in df.columns:
    df['Seasonality_Index'] = [1.1, 1.2, 0.9, 1.3, 1.0]

plt.scatter(df["Month"], df["Automobile_Sales"], s=df["Seasonality_Index"]*50, alpha=0.6)
plt.title("Seasonality Impact on Automobile Sales")
plt.xlabel("Month")
plt.ylabel("Automobile Sales")
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

if 'Price' not in df.columns:
    df['Price'] = df['Automobile_Sales'] * 1.5 + np.random.rand(len(df)) * 10

recession = df[df["Recession"] == 1]
sns.scatterplot(data=recession, x="Price", y="Automobile_Sales")
plt.title("Price vs Automobile Sales During Recession")
plt.show()

exp = df.groupby("Recession")["Advertising_Expenditure"].sum()
plt.pie(exp, labels=["Non‑Recession", "Recession"], autopct="%1.1f%%")
plt.title("Advertising Expenditure Distribution")
plt.show()

rec_exp = recession.groupby("Vehicle_Type")["Advertising_Expenditure"].sum()
plt.pie(rec_exp, labels=rec_exp.index, autopct="%1.1f%%")
plt.title("Advertisement Expenditure by Vehicle Type (Recession)")
plt.show()

import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

if 'Unemployment_Rate' not in df.columns:
    df['Unemployment_Rate'] = [5.5, 4.8, 8.2, 6.0, 5.0]

recession = df[df["Recession"] == 1]
sns.lineplot(data=recession, x="Unemployment_Rate", y="Automobile_Sales", hue="Vehicle_Type")
plt.title("Effect of Unemployment Rate on Vehicle Type and Automobile Sales During Recession")
plt.show()